In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('./classification220926/train.csv')
dftest = pd.read_csv('./classification220926/test.csv')


x = df.iloc[:,:-1]
x1 = dftest
y = df.loc[:,['income']]

print(x.value_counts('occupation'))
print(x.value_counts('workclass'))

occupation
 Prof-specialty       3724
 Craft-repair         3632
 Exec-managerial      3609
 Adm-clerical         3440
 Sales                3292
 Other-service        2975
 Machine-op-inspct    1811
 ?                    1668
 Transport-moving     1393
 Handlers-cleaners    1249
 Farming-fishing       888
 Tech-support          865
 Protective-serv       603
 Priv-house-serv       146
 Armed-Forces           10
dtype: int64
workclass
 Private             20410
 Self-emp-not-inc     2305
 Local-gov            1868
 ?                    1663
 State-gov            1201
 Self-emp-inc          987
 Federal-gov           854
 Without-pay            12
 Never-worked            5
dtype: int64

In [3]:
x.drop(['no', 'education','fnlwgt','native-country'], axis=1, inplace=True)


x1.drop(['no', 'education','fnlwgt','native-country'], axis=1, inplace=True)

In [4]:
x['abs'] = np.nan

x.loc[(x['education-num'] == 1) | (x['workclass'] == ' Never-worked'), 'abs'] = 0
x.loc[(x['workclass'] != ' Never-worked') & (x['education-num'] != 1), 'abs'] = 1

x1['abs'] = np.nan

x1.loc[(x['education-num'] == 1) | (x['workclass'] == ' Never-worked'), 'abs'] = 0
x1.loc[(x['workclass'] != ' Never-worked') & (x['education-num'] != 1), 'abs'] = 1

In [5]:
x.value_counts('abs')

abs
1.0    29254
0.0       51
dtype: int64

In [6]:

x.replace({'workclass':{'Never-worked':'whitehand','Without-pay':'littlework','State-gov':'gov',
                        'Local-gov':'gov','Federal-gov':'gov'}},inplace=True,regex=True)


x.replace({'marital-status' : {'Never-married':'single','Separated':'single','Widowed':'single','Married-spouse-absent':'single'
                               ,'Divorced':'single','Married-AF-spouse':'couple','Married-civ-spouse':'couple'}},
          inplace=True,regex=True)
x.replace({'relationship':{'Own-child':'couple','Other-relative':'other','Unmarried':'single','Not-in-family':'couple',
           'Husband':'couple','Wife':'couple'}},inplace=True,regex=True)


xstr = x[['workclass','marital-status','occupation','relationship','race','sex']]
xnum = x[['age','education-num','capital-gain','capital-loss','hours-per-week','abs']]




x1.replace({'workclass':{'Never-worked':'whitehand','Without-pay':'littlework','State-gov':'gov',
                        'Local-gov':'gov','Federal-gov':'gov'}},inplace=True,regex=True)


x1.replace({'marital-status' : {'Never-married':'single','Separated':'single','Widowed':'single','Married-spouse-absent':'single'
                               ,'Divorced':'single','Married-AF-spouse':'couple','Married-civ-spouse':'couple'}},
          inplace=True,regex=True)
x1.replace({'relationship':{'Own-child':'couple','Other-relative':'other','Unmarried':'single','Not-in-family':'couple',
           'Husband':'couple','Wife':'couple'}},inplace=True,regex=True)


xstr1 = x1[['workclass','marital-status','occupation','relationship','race','sex']]
xnum1 = x1[['age','education-num','capital-gain','capital-loss','hours-per-week','abs']]

In [7]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
encoder = LabelEncoder()
scaler = MinMaxScaler()
scaler2 = StandardScaler()

xstrdummy = pd.get_dummies(xstr)
xstr = xstrdummy
x = pd.concat([xstr,xnum],axis=1)

xstrdummy1 = pd.get_dummies(xstr1)
xstr1 = xstrdummy1
x1 = pd.concat([xstr1,xnum1],axis=1)
x

,workclass_ ?,workclass_ Private,workclass_ Self-emp-inc,workclass_ Self-emp-not-inc,workclass_ gov,workclass_ littlework,workclass_ whitehand,marital-status_ couple,marital-status_ single,occupation_ ?,...,race_ Other,race_ White,sex_ Female,sex_ Male,age,education-num,capital-gain,capital-loss,hours-per-week,abs
0,0,1,0,0,0,0,0,0,1,0,...,0,1,0,1,25,7,0,0,40,1.0
1,0,1,0,0,0,0,0,0,1,0,...,0,1,1,0,39,10,0,1721,55,1.0
2,0,1,0,0,0,0,0,0,1,0,...,0,0,1,0,35,13,0,0,50,1.0
3,0,1,0,0,0,0,0,0,1,0,...,0,1,1,0,64,11,0,0,40,1.0
4,0,1,0,0,0,0,0,1,0,0,...,0,1,0,1,24,10,0,0,70,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29300,0,1,0,0,0,0,0,0,1,0,...,1,0,0,1,20,9,0,0,40,1.0
29301,0,1,0,0,0,0,0,0,1,0,...,0,0,0,1,21,9,0,0,40,1.0
29302,0,0,0,1,0,0,0,0,1,0,...,0,1,0,1,18,6,0,0,40,1.0
29303,0,1,0,0,0,0,0,0,1,0,...,0,1,0,1,33,7,0,0,65,1.0
29304,1,0,0,0,0,0,0,0,1,1,...,0,1,1,0,65,9,0,0,40,1.0

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x, y, test_size=0.3,random_state=0)


from sklearn.ensemble import GradientBoostingClassifier
gb = GradientBoostingClassifier(learning_rate=0.1,n_estimators=180,random_state=0,
                                max_depth=4,min_samples_leaf=5)
gb.fit(x_train, y_train) #여기서 x_train은 이미 위에서 스케일링함

print(gb.score(x_train, y_train)) #훈련 데이터
print(gb.score(x_test, y_test)) #테스트 데이터

c:\Project\AI_Source\AI_01\venv\lib\site-packages\sklearn\ensemble\_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.8785648125578901
0.8751137397634213

In [8]:
dfsubmit = pd.read_csv('./classification220926/sample_submission.csv')
# 0.8751137397634213

In [9]:
dfsubmit['income'] = gb.predict(x1)
dfsubmit.to_csv('model07_CLA08.csv',index=False)

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x, y, test_size=0.3,random_state=1)


from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(random_state=42)
dt.fit(x_train, y_train) #여기서 x_train은 이미 위에서 스케일링함

print(dt.score(x_train, y_train)) #훈련 데이터
print(dt.score(x_test, y_test)) #테스트 데이터

0.9782089406717691
0.8140354868061874

In [11]:
from sklearn.ensemble import AdaBoostClassifier
adbc = AdaBoostClassifier(n_estimators=2000, random_state=42)
adbc.fit(x_train, y_train)


print(adbc.score(x_train, y_train)) #훈련 데이터
print(adbc.score(x_test, y_test)) #테스트 데이터

c:\Project\AI_Source\AI_01\venv\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.8717886218495589
0.870336669699727

In [42]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, ExtraTreesClassifier, BaggingClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegressionCV
from sklearn.ensemble import VotingClassifier
from catboost import CatBoostClassifier

models = [
    ('ada', AdaBoostClassifier(n_estimators=1000, random_state=40)),
    ('gbc', GradientBoostingClassifier(loss='exponential',learning_rate=0.1,n_estimators=180,random_state=40,
                                max_depth=4,min_samples_leaf=5)),
    ('rfc', RandomForestClassifier(n_estimators=1000, random_state=40, criterion='gini')),
    ('cbc', CatBoostClassifier(verbose = 300,random_state=0,bagging_temperature=100,max_bin=500,max_depth=4))
]

soft_vote  = VotingClassifier(models, voting='hard')
soft_vote.fit(x_train, y_train)

print(soft_vote.score(x_train, y_train)) #훈련 데이터
print(soft_vote.score(x_test, y_test)) #테스트 데이터

c:\Project\AI_Source\AI_01\venv\lib\site-packages\sklearn\preprocessing\_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Project\AI_Source\AI_01\venv\lib\site-packages\sklearn\preprocessing\_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Learning rate set to 0.037426
0:	learn: 0.6584953	total: 33.5ms	remaining: 33.5s
300:	learn: 0.2875207	total: 3s	remaining: 6.96s
600:	learn: 0.2732918	total: 6.08s	remaining: 4.04s
900:	learn: 0.2653831	total: 8.88s	remaining: 976ms
999:	learn: 0.2631722	total: 9.81s	remaining: 0us
0.8867059913225759
0.8756824385805277

In [43]:
dfsubmit = pd.read_csv('./classification220926/sample_submission.csv')
dfsubmit['income'] = soft_vote.predict(x1)
dfsubmit.to_csv('model07_CLA10.csv',index=False)

In [40]:
from catboost import CatBoostClassifier


cbc = CatBoostClassifier(verbose = 300,random_state=0,bagging_temperature=100,max_bin=500,max_depth=4)
cbc.fit(x_train, y_train) #여기서 x_train은 이미 위에서 스케일링함

print(cbc.score(x_train, y_train)) #훈련 데이터
print(cbc.score(x_test, y_test)) #테스트 데이터

Learning rate set to 0.037426
0:	learn: 0.6584953	total: 5.94ms	remaining: 5.93s
300:	learn: 0.2875207	total: 1.7s	remaining: 3.94s
600:	learn: 0.2732918	total: 3.33s	remaining: 2.21s
900:	learn: 0.2653831	total: 4.94s	remaining: 543ms
999:	learn: 0.2631722	total: 5.45s	remaining: 0us
0.8813922878174816
0.8751137397634213

In [15]:
from xgboost import XGBClassifier
booster = XGBClassifier(eta = 0.01)
booster.fit(x_train, y_train)


print(adbc.score(x_train, y_train)) #훈련 데이터
print(adbc.score(x_test, y_test)) #테스트 데이터

0.8717886218495589
0.870336669699727

In [9]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score, KFold

cv = KFold(n_splits=5, random_state=1, shuffle=True)
estimator = CatBoostClassifier()
params = {
      "random_state":[42],
      'learning_rate' : [ 0.01, 0.3],
      'bagging_temperature' :[0.01, 100.00],
      "n_estimators":[1000, 10000],
      "max_depth":[4, 16],
      'random_strength' :[0, 100],
      "colsample_bylevel":[0.4, 1.0],
      "l2_leaf_reg":[1e-8,3e-5],
      "min_child_samples": [5, 100],
      "max_bin": [200, 500],
      'od_type': ['IncToDec', 'Iter'],
  }


gridrf = GridSearchCV(estimator=estimator, param_grid=params,
                        cv=cv, verbose=-1, n_jobs=-1, refit=True)

gridrf.fit(x_train, y_train)

print("Best Estimator:\n", gridrf.best_estimator_)
print()
print("Best Params:\n", gridrf.best_params_)
print()
print("Best Score:\n", gridrf.best_score_)
print()

NameError: name 'CatBoostClassifier' is not defined

In [41]:
dfsubmit = pd.read_csv('./classification220926/sample_submission.csv')
dfsubmit['income'] = cbc.predict(x1)
dfsubmit.to_csv('model07_CLA09.csv',index=False)